package snastro.avvio.sbobinatura

import snastro.avvio.segnalazioneApp
import snastro.supporto.Segnalazione
import java.io.IOException
import java.nio.file.Files
import java.nio.file.Path

/** The folder name projects used before the Documento → Sbobinatura rename (ADR 0031). */
private const val CARTELLA_PRIMA_DEL_RINOMINO = "documenti"

/**
 * ADR 0031: renames a pre-rename project's `documenti/` to `sbobinature/` once, when the project is opened. The files
 * are derived (regenerated by the startup sweep, AC-185), so nothing is ever merged: if both folders exist, both are
 * left as they are and [segnala]led. A move that fails is [segnala]led too and never stops the project from opening:
 * the sweep then writes into a fresh `sbobinature/`.
 */
internal fun migraCartellaSbobinature(
    cartellaProgetto: Path,
    segnala: Segnalazione = segnalazioneApp,
    sposta: (Path, Path) -> Unit = { da, a -> Files.move(da, a) },
) {
    val vecchia = cartellaProgetto.resolve(CARTELLA_PRIMA_DEL_RINOMINO)
    val nuova = cartellaProgetto.resolve(ModuloSbobinatura.CARTELLA_SBOBINATURE)
    if (!Files.isDirectory(vecchia)) return
    if (Files.exists(nuova)) {
        segnala.segnala("ADR 0031: $vecchia resta accanto a $nuova, nessuno spostamento", null)
        return
    }
    try {
        sposta(vecchia, nuova)
    } catch (e: IOException) {
        segnala.segnala("ADR 0031: impossibile rinominare $vecchia in $nuova", e)
    } catch (e: SecurityException) {
        segnala.segnala("ADR 0031: impossibile rinominare $vecchia in $nuova", e)
    }
}
