package snastro.avvio.sbobinatura

import java.nio.file.Files
import java.nio.file.Path

/** The folder name projects used before the Documento → Sbobinatura rename (ADR 0031). */
private const val CARTELLA_PRIMA_DEL_RINOMINO = "documenti"

/**
 * ADR 0031: renames a pre-rename project's `documenti/` to `sbobinature/` once, when the project is opened. The files
 * are
 * derived (regenerated by the startup sweep, AC-185), so nothing is ever merged: if both folders exist, both are left
 * as they are.
 */
internal fun migraCartellaSbobinature(cartellaProgetto: Path) {
    val vecchia = cartellaProgetto.resolve(CARTELLA_PRIMA_DEL_RINOMINO)
    val nuova = cartellaProgetto.resolve(ModuloSbobinatura.CARTELLA_SBOBINATURE)
    if (Files.isDirectory(vecchia) && Files.notExists(nuova)) Files.move(vecchia, nuova)
}
